In [10]:
import numpy as np

# Arrays in Numpy

## Dimensions
1. Every array in numpy can be thought of as a matrix
2. You can perform several operations on these matrices using functions available in numpy itself
3. Let's see how we can create an array

In [11]:
a = np.array([0, 1, 2, 3]) # Manually creating a 1-D Numpy Array
print("1-D Numpy Array: ", a)
print()

print("Dimension of the Numpy Array: " , a.ndim) # Dimension of the Numpy Array
print()

print("Shape of the Numpy Array: ", a.shape) # Shape of the Numpy Array

1-D Numpy Array:  [0 1 2 3]

Dimension of the Numpy Array:  1

Shape of the Numpy Array:  (4,)


In [13]:
b = np.array([[1,2,3,4], [5,6,7,8]]) # Manually creating a 2-D Numpy Array
print("2-D Numpy Array:")
print(b)
print()

print("Dimension of the Numpy Array: " , b.ndim) # Dimension of the Numpy Array
print()

print("Shape of the Numpy Array: ", b.shape) # Shape of the Numpy Array

2-D Numpy Array:
[[1 2 3 4]
 [5 6 7 8]]

Dimension of the Numpy Array:  2

Shape of the Numpy Array:  (2, 4)


#### **3-D Numpy Array**

In [15]:
c = np.array([[[1], [2]], [[3], [4]]]) # Manually creating a 3-D Numpy Array
print("3-D Numpy Array:")
print(c)
print()

print("Dimension of the Numpy Array: " , c.ndim) # Dimension of the Numpy Array
print()

print("Shape of the Numpy Array: ", c.shape) # Shape of the Numpy Array

3-D Numpy Array:
[[[1]
  [2]]

 [[3]
  [4]]]

Dimension of the Numpy Array:  3

Shape of the Numpy Array:  (2, 2, 1)


### Functions for creating Numpy Arrays

In [16]:
a1 = np.arange(10)  # 0 .. n-1  (!)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
b1 = np.arange(1, 9, 2)  # start, end (exclusive), step
print(b1)
print()

c1 = np.linspace(0, 1, 6)  # start, end, num-points
print(c1)
print()

d = np.linspace(0, 1, 5, endpoint=False)
print(d)
print()

[1 3 5 7]

[0.  0.2 0.4 0.6 0.8 1. ]

[0.  0.2 0.4 0.6 0.8]



In [20]:
print("3-D Array of ones: ")
print(np.ones((3, 3)))
print()

print("2-D Array of zeros: ")
print(np.zeros((2, 2)))
print()

print("Identity Matrix: ")
print(np.eye(3))
print()

print("Diagonal Matrix: ")
print(np.diag(np.array([1, 2, 3, 4])))

3-D Array of ones: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

2-D Array of zeros: 
[[0. 0.]
 [0. 0.]]

Identity Matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Basic Data Types